name: Deploy DB Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy DB Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DB_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/db-repo
            git pull origin main
            docker-compose down
            docker-compose up -d --build
